services:

  mysql1:
    image: mysql:latest
    volumes:
      - mysql1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_1}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT_1}
    command: --default-time-zone='+00:00'
    ports:
      - '${MYSQL_TCP_PORT_1}:${MYSQL_TCP_PORT_1}'
    expose:
      - ${MYSQL_TCP_PORT_1}
    networks:
      - parcel-lockers-network

  mysql2:
    image: mysql:latest
    volumes:
      - mysql2:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_2}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT_2}
    command: --default-time-zone='+00:00'
    ports:
      - '${MYSQL_TCP_PORT_2}:${MYSQL_TCP_PORT_2}'
    expose:
      - ${MYSQL_TCP_PORT_2}
    networks:
      - parcel-lockers-network

  mysql3:
    image: mysql:latest
    volumes:
      - mysql3:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_3}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT_3}
    command: --default-time-zone='+00:00'
    ports:
      - '${MYSQL_TCP_PORT_3}:${MYSQL_TCP_PORT_3}'
    expose:
      - ${MYSQL_TCP_PORT_3}
    networks:
      - parcel-lockers-network

  mysql4:
    image: mysql:latest
    volumes:
      - mysql4:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_4}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT_4}
    command: --default-time-zone='+00:00'
    ports:
      - '${MYSQL_TCP_PORT_4}:${MYSQL_TCP_PORT_4}'
    expose:
      - ${MYSQL_TCP_PORT_4}
    networks:
      - parcel-lockers-network

  mysql5:
    image: mysql:latest
    volumes:
      - mysql5:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_5}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT_5}
    command: --default-time-zone='+00:00'
    ports:
      - '${MYSQL_TCP_PORT_5}:${MYSQL_TCP_PORT_5}'
    expose:
      - ${MYSQL_TCP_PORT_5}
    networks:
      - parcel-lockers-network

volumes:
  mysql1:
  mysql2:
  mysql3:
  mysql4:
  mysql5:

networks:
  parcel-lockers-network: