spring:
  application:
    name: parcel-machine-service
    db-record-freshness-threshold: PT24H

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
        order_updates: true
        order_inserts: true

overpass:
  base-url: https://overpass-api.de/api